# @package _global_

rewards:
  set_reward: B2Z1FlatLowLevel
  set_reward_date: 20260720
  only_positive_rewards: False
  reward_scales: {}

  reward_limit:
    soft_dof_pos_limit: 0.95
    soft_dof_vel_limit: 0.95
    soft_torque_limit: 0.9
    reward_limits_curriculum:
      soft_dof_pos_curriculum: False
      soft_dof_pos_initial_limit: 1.15
      soft_dof_pos_max_limit: 1.15
      soft_dof_pos_min_limit: 0.95
      soft_dof_pos_curriculum_degree: 0.0
      soft_dof_pos_curriculum_level_down_threshold: 40
      soft_dof_pos_curriculum_level_up_threshold: 42
      soft_dof_vel_curriculum: False
      soft_dof_vel_initial_limit: 1.15
      soft_dof_vel_max_limit: 1.25
      soft_dof_vel_min_limit: 0.95
      soft_dof_vel_curriculum_degree: 0.0
      soft_dof_vel_curriculum_level_down_threshold: 40
      soft_dof_vel_curriculum_level_up_threshold: 42
      soft_torque_curriculum: False
      soft_torque_initial_limit: 1.15
      soft_torque_max_limit: 1.25
      soft_torque_min_limit: 0.85
      soft_torque_curriculum_degree: 0.0
      soft_torque_curriculum_level_down_threshold: 40
      soft_torque_curriculum_level_up_threshold: 42

  reward_penalty_curriculum: False
  reward_initial_penalty_scale: 1.0
  reward_min_penalty_scale: 1.0
  reward_max_penalty_scale: 1.0
  reward_penalty_level_down_ave_goal_reached_rate: 0.0
  reward_penalty_level_up_ave_goal_reached_rate: 1.0
  reward_penalty_degree: 0.0
  num_compute_average_epl: 1
  reward_penalty_reward_names: []
