# @package _global_

obs:
  obs_dict:
    actor_obs: [
      dof_pos,
      relative_to_door,
      dof_vel,
      projected_gravity,
      door_dof_pos,
      base_lin_vel,
      base_ang_vel,
      hand_force,
      stage,
      privileged_door_info,
      delta_actions,
      hand_handle_transform,
      b2z1_commands,
    ]

    critic_obs: [
      dof_pos,
      relative_to_door,
      dof_vel,
      projected_gravity,
      door_dof_pos,
      base_lin_vel,
      base_ang_vel,
      hand_force,
      stage,
      privileged_door_info,
      delta_actions,
      hand_handle_transform,
      transition,
      complete,
      time_in_stage,
      actual_time_in_stage,
      total_time,
      b2z1_commands,
    ]

  obs_auxiliary: {}

  obs_scales: {
    dof_pos: 1.0,
    relative_to_door: 1.0,
    dof_vel: 0.05,
    projected_gravity: 1.0,
    door_dof_pos: 1.0,
    base_lin_vel: 1.0,
    base_ang_vel: 0.5,
    hand_force: 0.01,
    stage: 1.0,
    privileged_door_info: 1.0,
    delta_actions: 1.0,
    hand_handle_transform: 1.0,
    transition: 1.0,
    complete: 1.0,
    time_in_stage: 1.0,
    actual_time_in_stage: 1.0,
    total_time: 1.0,
    b2z1_commands: 1.0,
  }

  noise_scales: {
    dof_pos: 0.01,
    relative_to_door: 0.0,
    dof_vel: 0.2,
    projected_gravity: 0.0,
    door_dof_pos: 0.0,
    base_lin_vel: 0.0,
    base_ang_vel: 0.0,
    hand_force: 0.0,
    stage: 0.0,
    privileged_door_info: 0.0,
    delta_actions: 0.0,
    hand_handle_transform: 0.0,
    transition: 0.0,
    complete: 0.0,
    time_in_stage: 0.0,
    actual_time_in_stage: 0.0,
    total_time: 0.0,
    b2z1_commands: 0.0,
  }

  add_noise_currculum: False
  noise_initial_value: 0.05
  noise_value_max: 1.00
  noise_value_min: 0.00001
  soft_dof_pos_curriculum_degree: 0.00001
  soft_dof_pos_curriculum_level_down_threshold: 100
  soft_dof_pos_curriculum_level_up_threshold: 900

  obs_dims:
    - dof_pos: ${robot.dof_obs_size}
    - hand_force: 3
    - relative_to_door: 9
    - dof_vel: ${robot.dof_obs_size}
    - projected_gravity: 3
    - door_dof_pos: 2
    - base_lin_vel: 3
    - base_ang_vel: 3
    - stage: ${eval:'len(${env.config.max_stage_time})'}
    - privileged_door_info: 8
    - hand_handle_transform: 9
    - b2z1_commands: 10
    - transition: 1
    - complete: 1
    - time_in_stage: 1
    - actual_time_in_stage: 1
    - total_time: 1
    - delta_actions: ${eval:'len(${env.config.delta_action_indices})'}
