# @package _global_

defaults:
  - loco_manip_base

# Env structure
env:
  _target_: groot.rl.envs.loco_manip.walk_stand_place_grasp_turn_homie.WalkStandPlaceGraspTurnHomie
  config:
    max_episode_length_s: 12
    
    normalization:
      clip_actions: 100.0
      clip_observations: 100.0

    # simulator:
    #   sim:
    #     fps: 200 # 1/dt , dt = 0.005
    #     control_decimation: 4  # decimation
    #     substeps: 1
    termination:
      terminate_when_close_to_dof_pos_limit: False
      terminate_when_close_to_dof_vel_limit: False
      terminate_when_close_to_torque_limit: False
      terminate_by_contact: False
      terminate_by_gravity: False
      terminate_by_low_height: False
      terminate_by_hand_object_contact: False
      terminate_by_large_homie_linvel_command: False
      terminate_object_by_low_height: True
      terminate_by_face_mul: True
      terminate_by_throw_object: True
      terminate_by_fast_right_arm_qvel: True
      terminate_by_linvel_x_when_near_front_object: False
      terminate_by_linvel_y_when_near_front_object: False
      terminate_by_angvel_when_near_front_object: False
      terminate_by_xy_far_from_front_object_init_pos: False
      terminate_by_finger_qvel_during_right_arm_qvel: False
      terminate_by_hold_object_tray_distance: True
      
    termination_scales:
      termination_close_to_dof_pos_limit : 0.98
      termination_close_to_dof_vel_limit : 0.98
      termination_close_to_torque_limit : 0.98
      termination_gravity_x : 0.5
      termination_gravity_y : 0.5
      termination_min_base_height : 0.3
      termination_contact_force : 10.0
      termination_large_homie_linvel_command_threshold : 0.75
      termination_object_by_low_height_threshold : 0.6
      termination_hold_object_threshold: 0.1
      termination_fast_right_arm_qvel_threshold: 3.14 # 0.314
      termination_finger_qvel_during_right_arm_qvel_threshold: 0.5
      termination_hold_object_tray_distance_threshold: 0.16
      homie_command_linvel_xy_over_threshold_2x: 0.7
      homie_command_angvel_over_threshold_2x: 0.7
      robot_to_init_front_object_distance_threshold_2x: 1.7
    termination_probality:
      terminate_when_close_to_dof_pos_limit: 0.25
      terminate_when_close_to_dof_vel_limit: 0.25
      terminate_when_close_to_torque_limit: 0.25

    termination_large_homie_linvel_command_curriculum:
      enable: False
      init_limit: 0.75
      upper_limit: 1.5
      lower_limit: 0.5
      level_up_episode_length: 285 # episode_length_s is 6 for now
      level_down_episode_length: 100
      degree_change: 0.00005 # 0.7 / 0.0001 = 7000 iters

    termination_curriculum:
      level_down_ave_goal_reached_rate: 0.6
      level_up_ave_goal_reached_rate: 0.96
      degree: -0.00008
      min_level: 0.1
      max_level: 1.0
      initial_level: 1.0
      # min_level is the hardest level
    
    clip_homie_command: True
    clip_homie_linvel_x_threshold: 0.5
    clip_homie_linvel_y_threshold: 0.5
    clip_homie_angvel_threshold: 1.0
    clip_homie_lower_height_threshold: 0.3
    clip_homie_upper_height_threshold: 0.75
    clip_homie_torso_roll_lower_threshold: -0.5
    clip_homie_torso_roll_upper_threshold: 0.5
    clip_homie_torso_pitch_lower_threshold: -0.5
    clip_homie_torso_pitch_upper_threshold: 0.5
    clip_homie_torso_yaw_lower_threshold: -0.5
    clip_homie_torso_yaw_upper_threshold: 0.5

    clip_upper_actions: False
    clip_upper_actions_threshold: 0.5
    arm_vel_threshold: 0.2

    noise_to_initial_level: 0
    init_noise_scale: 
      dof_pos: 0.1
      dof_vel: 0.15
      root_pos: 0.05
      root_rot: 10 # degree, * 3.14 / 180
      root_vel: 0.01
      root_ang_vel: 0.01

    task:
      type: "manipulation"
      name: "walk_stand_place_grasp_turn_homie"
      objects: [
        "table_grid",
        "hold_object",
        "front_object",
        "back_object",
        "tray_object",
        # "cube"
      ]
      hold_object: "hold_object"
      front_object: "front_object"
      back_object: "back_object"
      tray_object: "tray_object"
      max_object_number: 12
      thershold: 0.05
      hold_object_contact_sensor: True
      front_object_contact_sensor: True
      back_object_contact_sensor: False # NOTE teacher does not use back object
      manipulate_hand: "right_hand_palm_link"
      which_hand: "right_hand"
    
    # only used for mannualy reset task
    bottle_pos_range_x: [-0.02, 0.0]
    bottle_pos_range_y: [-0.01, 0.01]
    bottle_pos_range_z: [0.9, 1.2]

    max_consecutive_success_frames: 50

    ref_height: 0.75
    reset_task_every_n_steps: 1000
    goal_pos: [1.0, 0.0, 0.875]
    randomize_init_pos: True
    randomize_init_pos_range:
      x: [1.6, 1.7]
      y: [-0.01, 0.01]
      vel: [-0.5, 0.5]
    # lift_goal_offset_pelvis: [0.3, 0.0, 0.3]
    # lift_goal_offset_pelvis: [0.3, -0.2, 0.2]
    lift_goal_offset_pelvis: [0.3, -0.1, 0.3]
    award_remaining_time_on_advance: True
    reset_on_complete: False
    no_reward_for_awarded_time: False
    accumulate_stage_reward: False
    stage_reward_scale: [1.0, 1.0, 1.0, 1.0, 1.0]
    # max_stage_time: [200, 300]
    # max_stage_time: [150, 100]
    max_stage_time: [300, 50, 50, 100, 100] # walk place grasp turn
    homie_command_scale: 1.0

    delta_action_indices: [
      0, 1, 2,  # homie command
      3, 4, 5, 6, 7, 8, 9, # right arm
      10  # finger primitive
    ]
    delta_action_scale: 0.1
    reset_delta_actions_with_backmap: True
    no_delta_vel: True
    zero_vel: True
    zero_finger: False

    enable_staged_reset: False
    staged_reset_ratios: [0.1, 0.1, 0.1, 0.6, 0.1]
    staged_reset_max_samples_per_stage: 200

    target_root_vel: 0.5

    hold_object_tray_distance_threshold: 0.3
    hold_object_hand_distance_threshold: 0.2
    throw_object_contact_force_threshold: 1.0
    termin_hold_object_hand_distance_threshold: 0.1

    

    reset_from_teleop_start: False

    reset_from_dataset:
      enable: True
      reset_from_teleop_curriculum: False
      motion_files:
        # - ../../data/motions/g1_wsg/debug_dataset/record_2025-09-29_14-17-14.npz
        # - ../../data/motions/g1_wsg/debug_dataset/record_2025-09-29_14-25-24.npz
        # - ../../data/motions/g1_wsg/debug_dataset/record_2025-09-29_14-26-15.npz
        # - ../../data/motions/g1_wsg/debug_dataset/record_2025-09-29_14-26-56.npz
        # - groot/rl/data/motions/g1_wsg/debug_dataset/record_2025-09-29_14-17-14.npz
        # - groot/rl/data/motions/g1_wsg/debug_dataset/record_2025-09-29_14-25-24.npz
        # - groot/rl/data/motions/g1_wsg/debug_dataset/record_2025-09-29_14-26-15.npz
        # - groot/rl/data/motions/g1_wsg/debug_dataset/record_2025-09-29_14-26-56.npz


        # - groot/rl/data/motions/g1_wsg/debug_54spacing/record_2025-09-29_16-51-44.npz
        # - groot/rl/data/motions/g1_wsg/debug_54spacing/record_2025-09-29_16-52-24.npz
        # - groot/rl/data/motions/g1_wsg/debug_54spacing/record_2025-09-29_16-52-59.npz

        # - groot/rl/data/motions/g1_wsg/grasp_forever/record_2025-09-29_17-50-02.npz

        # - groot/rl/data/motions/g1_wsg/no_move_grasp/record_2025-09-29_18-38-37.npz

        # - groot/rl/data/motions/g1_wsg/wave_left_right/record_2025-09-29_18-45-08.npz

        # - groot/rl/data/motions/g1_wsg/fix_bug/record_2025-09-29_19-05-57.npz
        # - groot/rl/data/motions/g1_wsg/fix_bug/record_2025-09-29_19-06-46.npz
        # - groot/rl/data/motions/g1_wsg/fix_bug/record_2025-09-29_19-09-17.npz
        # - groot/rl/data/motions/g1_wsg/fix_bug/record_2025-09-29_19-10-06.npz
        # - groot/rl/data/motions/g1_wsg/fix_bug/record_2025-09-29_19-11-54.npz
        # - groot/rl/data/motions/g1_wsg/fix_bug/record_2025-09-29_19-13-11.npz
        # - groot/rl/data/motions/g1_wsg/fix_bug/record_2025-09-29_19-14-03.npz

        # with homie command
        # - groot/rl/data/motions/g1_wsg/with_homie_command/record_2025-09-30_14-33-02.npz
        # - groot/rl/data/motions/g1_wsg/with_homie_command/record_2025-09-30_14-34-27.npz
        # - groot/rl/data/motions/g1_wsg/with_homie_command/record_2025-09-30_14-35-13.npz
      use_motion_file_dir: True
      # motion_file_dir: "groot/rl/data/motions/g1_wsppt/debug_demos"
      # motion_file_dir: "groot/rl/data/motions/g1_wsppt/slow_pp_middle"
      # motion_file_dir: "groot/rl/data/motions/g1_wsdpt/5demo_debug"
      # motion_file_dir: "groot/rl/data/motions/g1_wsdpt/1demo_thick_30mm"
      # motion_file_dir: "groot/rl/data/motions/g1_wsdpt/1demo_lowheight_debug"
      # motion_file_dir: "groot/rl/data/motions/g1_wsdpt/2demo_30cm_50cm"
      motion_file_dir: "groot/rl/data/motions/g1_wsdpt/33demos_675_775"


      device: ""
      num_per_sample: 10
      sample_interval_s: 0.1
      resample_every: 1000

# Globally accessible parameters
log_task_name: walk_stand_place_grasp_turn_homie
